#	Makefile fuer Scrabble
#	
#	Wolfgang Laufhher
#
#	Thu Feb  9 20:16:47 GMT 1995

OBJECTS=q j x y

scrabble.dvi:	scrabble.tex
	latex scrabble.tex

scrabble.tex: $(OBJECTS) scrabble
	scrabble $(OBJECTS) > scrabble.tex

j:	j.unsort
	sort j.unsort > j

q:	q.unsort
	sort q.unsort > q

x:	x.unsort
	sort x.unsort > x

y:	y.unsort
	sort y.unsort > y
